### ISSUE TITLE
NodeJS: the node_module parser returns undefined

### ISSUE THREAD

**Issue by mateeyow** [snowplow-referer-parser/referer-parser#108]
Hi, I'm currently using your node_module on node, but I've tried using your application with the sample you gave on the README page:

``` javascript
var Referer = require('referer-parser')
var referer_url = 'http://www.snowplowanalytics.com/about/team'
var current_url = 'http://www.snowplowanalytics.com/account/profile'
var r = Referer(referer_url, current_url)
```

And I've checked the output of **r** but the result is undefined.

> Node version - v0.12.0
> NPM version - 2.7.0

**Comment by mateeyow** [comment]
I've also tried upgrade the node to:
> Node version - v0.12.5 
> NPM version - 2.11.2
Still no luck.

**Comment by BenFradet** [comment]
migrated to https://github.com/snowplow-referer-parser/nodejs-referer-parser/issues/4
