### ISSUE TITLE
Store internal domains in a set rather than a list

### ISSUE THREAD

**Issue by fblundun** [snowplow-referer-parser/referer-parser#117]
[Here](https://github.com/snowplow/referer-parser/blob/270109b02c6155b8bf09f1f6f71c54eb0933ab49/java-scala/src/main/java/com/snowplowanalytics/refererparser/Parser.java#L138-L141)

Since the only thing we do with the collection of internal domains is check whether a given string is a member.

**Comment by BenFradet** [comment]
Migrated to https://github.com/snowplow-referer-parser/java-referer-parser/issues/8
