### ISSUE TITLE
NodeJS:  How can I update yaml file using `npm update referer-parser`?

### ISSUE THREAD

**Issue by valeeum** [snowplow-referer-parser/referer-parser#126]
I'm trying to update my node referer-parser package so that it pulls in the latest yaml file.  How can I pull this file in which was updated 8months ago into the package that was updated 3 years ago?   Is there any way to rev the 0.0.3 package to 0.0.4 so npm update works?

**Comment by freshlogic** [comment]
I had the same problem so I decided to fork and push a scoped package to NPM: https://www.npmjs.com/package/@mediocre/referer-parser

**Comment by BenFradet** [comment]
repo moved to https://github.com/snowplow-referer-parser/nodejs-referer-parser closing
