### ISSUE TITLE
Proposition: Split data and parsers to separate repos

### ISSUE THREAD

**Issue by danm** [snowplow-referer-parser/referer-parser#140]
On the back of the work which ua-parser did with their repo's i'd like to suggest that we split referee-parser into different repo's and have a Core repo which contains the data.

All different language parsers have their own repo which use Core as a dependancy.

If the community wants to update or fork their own data in Core, it can easily be kept up to date for all parsers.

**Comment by alexanderdean** [comment]
+1 from me, I think this is a great idea and have wanted to do this for a while...

(Related, I'd also like to MaxMind-style decouple the library from the file, so you don't have to upgrade the library to use a newer version of the file)...

**Comment by calbatron** [comment]
In the docs it mentions the data was originally forked from Piwik's dataset. Was there a conscious decision not to continue to use theirs? There seem to be pros and cons to both - the dream would be a single source of truth for this data which is kept up to date by Piwik, Snowplow and the community.

**Comment by alexanderdean** [comment]
If the Piwik project would like to start using referer-parser-php that would be cool! But totally up to them of course.

**Comment by alexanderdean** [comment]
This has started happening - we are moving towards a Maxmind-style model, where there is a monthly release of the data file, and the individual libraries are updated to load the data file.

Decoupling the database release process from the libraries makes sense given that they have drastically different release cadences.

I will keep this ticket open to track this work. Any maintainer who wants a dedicated repo, please let me know and I will create one for them. We will crack on with the Java-Scala library migration and updating.

**Comment by alexanderdean** [comment]
This is ongoing: https://github.com/snowplow-referer-parser

**Comment by BenFradet** [comment]
done closing
