### ISSUE TITLE
The java enum Medium is missing the entry PAID

### ISSUE THREAD

**Issue by mambistats** [snowplow-referer-parser/referer-parser#162]
Is this code still maintained? This bug must be there for at least 5 years ... or is this code deprecated?

**Comment by BenFradet** [comment]
it's still maintained however we don't have a lot of cycles to spend on it at the moment.

**Comment by mambistats** [comment]
Pooh ... I already thought I am using the wrong code ... ;)

Von: Ben Fradet <notifications@github.com>
Antworten an: snowplow/referer-parser <reply@reply.github.com>
Datum: Dienstag, 10. Oktober 2017 um 19:16
An: snowplow/referer-parser <referer-parser@noreply.github.com>
Cc: Frank Kemmer <frank.kemmer@1und1.de>, Author <author@noreply.github.com>
Betreff: Re: [snowplow/referer-parser] The java enum Medium is missing the entry PAID (#162)


it's still maintained however we don't have a lot of cycles to spend on it at the moment.

**Comment by BenFradet** [comment]
migrated to snowplow-referer-parser/jvm-referer-parser#14
