### ISSUE TITLE
PHP paid medium

### ISSUE THREAD

**Issue by ndberg** [snowplow-referer-parser/referer-parser#192]
It looks like the PHP library is still missing the paid medium?

Is this library still maintained?

**Comment by BenFradet** [comment]
Hey @ndberg , we'll be moving the php library to its own repo shortly: https://github.com/snowplow-referer-parser/php-referer-parser.

While we'll be accepting PRs, we won't actively maintain the php library and are looking for new maintainers.

**Comment by topoff** [comment]
Ok thx, I'll take a look at the paid medium to make a pr when you moved the repo.

**Comment by ndberg** [comment]
Ok thx, I'll take a look at the paid medium to make a pr when you moved the repo.

**Comment by BenFradet** [comment]
migrated to https://github.com/snowplow-referer-parser/php-referer-parser/issues/3, closing
