### ISSUE TITLE
referers-latest.yml on S3 is returning 404

### ISSUE THREAD

**Issue by cipater** [snowplow-referer-parser/referer-parser#210]
The referers-latest.yml file at https://s3-eu-west-1.amazonaws.com/snowplow-hosted-assets/third-party/referer-parser/referers-latest.yml is currently returning a 404

**Comment by yugolova** [comment]
Hi @cipater!

We're checking this now and will post here as soon as we have more information.

**Comment by jrluis** [comment]
Hi @cipater,

Can you use the following url: https://snowplow-hosted-assets.s3-eu-west-1.amazonaws.com/third-party/referer-parser/referers-latest.yaml

One question, where did you got the link you are using?

Regards

**Comment by cipater** [comment]
Hi @jrluis,

The link you provided works, thanks!

The link I pasted is mentioned in the README.md file within this repository:

https://github.com/snowplow-referer-parser/referer-parser/blob/6c68c1ad2136f3874da0477c903b5f203160f53f/README.md#L15
