### ISSUE TITLE
referers-latest.yaml link is broken

### ISSUE THREAD

**Issue by jrluis** [snowplow-referer-parser/referer-parser#211]
In the readme file the link to https://s3-eu-west-1.amazonaws.com/snowplow-hosted-assets/third-party/referer-parser/referers-latest.yml isn't working.

The following link is working: https://snowplow-hosted-assets.s3-eu-west-1.amazonaws.com/third-party/referer-parser/referers-latest.yaml

**Comment by dilyand** [comment]
Fixed by 4898cdc04007973b4ae85b1277522b23179fea36
