### ISSUE TITLE
Create explicit tests to express the recursive check logic

### ISSUE THREAD

**Issue by alexanderdean** [snowplow-referer-parser/referer-parser#23]
Basically, the v1 library was looking for exact matches even www.google.com vs google.com

That approach is actually flawed:
1. Social networks often let users have their own subdomain, and you can't obviously list all of them
2. Yahoo! puts its search engine on load-balanced subdomains, and that's an unpredictable list

So this version instead tries multiple lookups:
- It tries the host, then the host + path, then the host + one-level path
- Then strips off a subdomain and tries again

We should write some explicit tests into the Specs2 test suite to check that this recursion logic works correctly.

/cc @donspaulding

**Comment by BenFradet** [comment]
migrated to snowplow-referer-parser/jvm-referer-parser#11
