### ISSUE TITLE
Re-factor Ruby library

### ISSUE THREAD

**Issue by alexanderdean** [snowplow-referer-parser/referer-parser#26]
Architecture is very OO and convoluted.

Move towards similar architecture to the Scala version: a Parser module which includes one-time instantiation, and then a static parse() method which returns a Referer object for a given URL.

@Tombar has moved it in the right direction with a public parse() method (https://github.com/Tombar/referer-parser/commit/a280d9ef1b7dd37bebf88f5f0b49ea245f05908b).

**Comment by BenFradet** [comment]
Migrated to https://github.com/snowplow-referer-parser/ruby-referer-parser/issues/7
