### ISSUE TITLE
Bug in ASP.NET library parsing search.tb.ask.com

### ISSUE THREAD

**Issue by alexanderdean** [snowplow-referer-parser/referer-parser#49]
Ticket based on #48.

Believe the bad URI fed in was: http://search.tb.ask.com/search/GGmain.jhtml

@aposashenko could you provide more information (e.g. on error message) and exact URL used here?

**Comment by BenFradet** [comment]
migrated to https://github.com/snowplow-referer-parser/dotnet-referer-parser/issues/4
