### ISSUE TITLE
Make JSON the standard format loaded by the libraries

### ISSUE THREAD

**Issue by alexanderdean** [snowplow-referer-parser/referer-parser#5]
Two reasons for this:
1. JSON seems faster to load than YAML in most languages (see https://github.com/tobie/ua-parser/issues/117)
2. More languages have JSON handling built-in than YAML (e.g. Python)

This would involve updating the Java/Scala and Ruby ports, and making @donspaulding's `build_json.py` a standard part of the distribution for all ports.

**Important note:** we would still keep the master copy of the database in YAML for readability/editability purposes.

**Comment by BenFradet** [comment]
migrated to the different repos, closing
