### ISSUE TITLE
Bug in Python module

### ISSUE THREAD

**Issue by dasolma** [snowplow-referer-parser/referer-parser#53]
I got the error: 

> > > from referer_parser import Referer
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "C:\Python27\lib\site-packages\referer_parser__init__.py", line 32, in <
> > > module>
> > >     REFERERS = load_referers(JSON_FILE)
> > >   File "C:\Python27\lib\site-packages\referer_parser__init__.py", line 21, in l
> > > oad_referers
> > >     params = list(map(text_type.lower, config['parameters']))
> > > TypeError: descriptor 'lower' requires a 'unicode' object but received a 'str'

i fix it temporaly modifing `__init__.py`, load_referers function:

```
if 'parameters' in config:
    p = config['parameters']
    if text_type == unicode:
        p = unicode(config['parameters'])
    params = list(map(text_type.lower, p))
```

Python 2.7, SO:Windows 7

**Comment by BenFradet** [comment]
Migrated to https://github.com/snowplow-referer-parser/python-referer-parser/issues/5
