### ISSUE TITLE
Can't use composer - possibility for a phar file?

### ISSUE THREAD

**Issue by morrow95** [snowplow-referer-parser/referer-parser#78]
Came across this tonight.  I am interested in the php to parse domain and search terms out of url logs.  Problem is I cannot use composer with my current server (WHM/Cpanel setup)... I came across this situation once before, however, they also offered a phar file of everything bundled which I could use without problems and eliminated the need for composer.

Any chance of this happening?

**Comment by morrow95** [comment]
+1

**Comment by BenFradet** [comment]
migrated to https://github.com/snowplow-referer-parser/php-referer-parser/issues/5
